before:
  hooks:
    - go mod tidy
    - go generate ./...
    - govulncheck ./...
    - actionlint
    - golangci-lint run

gomod:
  proxy: true

builds:
  - main: ./cmd/ttrpcurl
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -buildid=
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    goarch:
      - amd64
      - arm64
      - s390x
      - ppc64le
      - riscv64
    goos:
      - linux
      - darwin
    mod_timestamp: "{{ .CommitTimestamp }}"

checksum:
  disable: false

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds_info:
      group: root
      owner: root
      mode: 0755
      mtime: 1970-01-01T00:00:00.000000001Z
    files:
      - LICENSE
      - info:
          group: root
          owner: root
          mode: 0644
          mtime: 1970-01-01T00:00:00.000000001Z

release:
  github:
    owner: katexochen
    name: ttrpcurl
  draft: true
  replace_existing_draft: true
  mode: replace

changelog:
  use: github
  sort: asc
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
